# Generated by Django 3.0.2 on 2020-01-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='IDSubject',
            field=models.FloatField(),
        ),
    ]
