# Generated by Django 3.0.2 on 2020-01-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_auto_20200129_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='IDSubject',
            field=models.IntegerField(),
        ),
    ]
