# Generated by Django 3.0.2 on 2020-01-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_auto_20200129_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='zwrist',
            field=models.FloatField(),
        ),
    ]
