# Generated by Django 3.0.2 on 2020-01-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0007_auto_20200129_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='IDSubject',
        ),
        migrations.AddField(
            model_name='subject',
            name='HEIGHT',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='WEIGHT',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='activity',
            field=models.IntegerField(),
        ),
    ]
