# Generated by Django 3.0.2 on 2020-01-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0008_auto_20200131_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='activity',
            field=models.IntegerField(null=True),
        ),
    ]
