# Generated by Django 3.0.2 on 2020-01-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0009_auto_20200131_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='HEIGHT',
            new_name='IDSubject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='WEIGHT',
        ),
        migrations.AlterField(
            model_name='subject',
            name='activity',
            field=models.FloatField(null=True),
        ),
    ]
