# Generated by Django 3.0.2 on 2020-01-31 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0010_auto_20200131_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='IDSubject',
        ),
    ]
